= metaSearch
Author Thibault Daccord
:doctype: article
:encoding: utf-8
:lang: en
:toc: left
:numbered:


== introduction
Ce projet est un plugin google chrome (bientot sur firefox) qui permet de faire des recherches automatiques sur des sous liens de la page. (ex filtrer toutes les annonces des processeurs d'intel,sur le site de la fnac pour avoir que l'annonce avec la chaine de caratere "Intel Core i5 2320 / 3 GHz processeur" dans la page.

[WARNING]
====
Ce projet est encore en version beta
====

[colophon]
== Utilisation

importer directement le plugin sur google chrome, ouvrir la console puis lancer le module avec le bouton "test !".
Pour le personnaliser il faut modifier test.js dans la partie:

		$.ajax({
	   url : 'http://recherche.fnac.com/SearchResult/ResultList.aspx?Search=i5&SFilt=0.0_15300.0!9%2c35760!23&sft=1&sl=0.845',//à mettre le site voulu
	   type : 'GET',
	   dataType : 'html',
	   success : function(data, statut){
		 jQuery(data).find('li').each(function() {
	  // Do something to each item here...
		      if(($(this)).has( 'a' ).length){
		         $(this).find('a').each(function() {
		              nom=$(this).html();
		              href = $(this).attr('href');
		              //console.log(href);
                  data2="";
                  href2=href;
                  if(href!=null)
                        if(href.indexOf('http')!=-1 && href.indexOf('http://www.fnac.com/mp')!=-1)//à mettre le site voulu
                        {
          		              downloadUrl(href, function(data2,statues,href2) {
                		              if(data2.responseText.indexOf('Intel Core i5 2320 / 3 GHz processeur')!=-1){//à mettre la chaine voulue
                		                  console.log("href valide ="+href2);
                                      console.log(href2);
                                      console.log(data2.responseText.indexOf("Intel Core i5 2320 / 3 GHz processeur"));//à mettre la chaine voulue
                		              }
                                  else{
                                      //console.log("bad req"+href2);
                                  }
          		                });
                      }
		        });

		    };
		 });
